// Date: 5/14/2014 11:28:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package net.modyssey.teleporters.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelStation extends ModelBase
{
  //fields
    ModelRenderer Base1;
    ModelRenderer Base2;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Keyboard_Bottom;
    ModelRenderer Keyboard_Top;
    ModelRenderer Monitor_Base;
    ModelRenderer Monitor_Bulk;
    ModelRenderer Top_Frame;
    ModelRenderer Side_Frame1;
    ModelRenderer Side_Frame2;
    ModelRenderer Stand;
    ModelRenderer Stand_Connector;
    ModelRenderer Battery;
    ModelRenderer Cords_Stand;
    ModelRenderer Battery_Top;
    ModelRenderer Cords_Monitor;
    ModelRenderer Cords_Link;
  
  public ModelStation()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Base1 = new ModelRenderer(this, 0, 0);
      Base1.addBox(-8F, 0F, -8F, 16, 1, 16);
      Base1.setRotationPoint(0F, 21F, 0F);
      Base1.setTextureSize(128, 128);
      Base1.mirror = true;
      setRotation(Base1, 0F, 0F, 0F);
      Base2 = new ModelRenderer(this, 0, 0);
      Base2.addBox(0F, 0F, 0F, 16, 1, 16);
      Base2.setRotationPoint(-8F, 10F, -8F);
      Base2.setTextureSize(128, 128);
      Base2.mirror = true;
      setRotation(Base2, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 17);
      Leg1.addBox(0F, 0F, 0F, 2, 15, 2);
      Leg1.setRotationPoint(6F, 9F, -8F);
      Leg1.setTextureSize(128, 128);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 17);
      Leg2.addBox(0F, 0F, 0F, 2, 15, 2);
      Leg2.setRotationPoint(6F, 9F, 6F);
      Leg2.setTextureSize(128, 128);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 17);
      Leg3.addBox(0F, 0F, 0F, 2, 15, 2);
      Leg3.setRotationPoint(-8F, 9F, -8F);
      Leg3.setTextureSize(128, 128);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 0, 17);
      Leg4.addBox(0F, 0F, 0F, 2, 15, 2);
      Leg4.setRotationPoint(-8F, 9F, 6F);
      Leg4.setTextureSize(128, 128);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Keyboard_Bottom = new ModelRenderer(this, 8, 22);
      Keyboard_Bottom.addBox(0F, 0F, -1F, 12, 1, 3);
      Keyboard_Bottom.setRotationPoint(-6F, 9F, 5F);
      Keyboard_Bottom.setTextureSize(128, 128);
      Keyboard_Bottom.mirror = true;
      setRotation(Keyboard_Bottom, 0F, 0F, 0F);
      Keyboard_Top = new ModelRenderer(this, 8, 17);
      Keyboard_Top.addBox(0F, 0F, 0F, 12, 2, 3);
      Keyboard_Top.setRotationPoint(-6F, 8F, 1F);
      Keyboard_Top.setTextureSize(128, 128);
      Keyboard_Top.mirror = true;
      setRotation(Keyboard_Top, 0F, 0F, 0F);
      Monitor_Base = new ModelRenderer(this, 0, 34);
      Monitor_Base.addBox(0F, 0F, 0F, 12, 3, 9);
      Monitor_Base.setRotationPoint(-6F, 7F, -8F);
      Monitor_Base.setTextureSize(128, 128);
      Monitor_Base.mirror = true;
      setRotation(Monitor_Base, 0F, 0F, 0F);
      Monitor_Bulk = new ModelRenderer(this, 0, 47);
      Monitor_Bulk.addBox(0F, 0F, 0F, 10, 8, 8);
      Monitor_Bulk.setRotationPoint(-5F, -1F, -8F);
      Monitor_Bulk.setTextureSize(128, 128);
      Monitor_Bulk.mirror = true;
      setRotation(Monitor_Bulk, 0F, 0F, 0F);
      Top_Frame = new ModelRenderer(this, 38, 17);
      Top_Frame.addBox(0F, 0F, 0F, 10, 2, 2);
      Top_Frame.setRotationPoint(-5F, -2F, -1F);
      Top_Frame.setTextureSize(128, 128);
      Top_Frame.mirror = true;
      setRotation(Top_Frame, 0F, 0F, 0F);
      Side_Frame1 = new ModelRenderer(this, 64, 9);
      Side_Frame1.addBox(0F, 0F, 0F, 1, 9, 2);
      Side_Frame1.setRotationPoint(5F, -2F, -1F);
      Side_Frame1.setTextureSize(128, 128);
      Side_Frame1.mirror = true;
      setRotation(Side_Frame1, 0F, 0F, 0F);
      Side_Frame1.mirror = true;
      Side_Frame2 = new ModelRenderer(this, 64, 9);
      Side_Frame2.addBox(0F, 0F, 0F, 1, 9, 2);
      Side_Frame2.setRotationPoint(-6F, -2F, -1F);
      Side_Frame2.setTextureSize(128, 128);
      Side_Frame2.mirror = true;
      setRotation(Side_Frame2, 0F, 0F, 0F);
      Side_Frame2.mirror = false;
      Stand = new ModelRenderer(this, 42, 34);
      Stand.addBox(0F, 0F, 0F, 4, 8, 4);
      Stand.setRotationPoint(-2F, 13F, -2F);
      Stand.setTextureSize(128, 128);
      Stand.mirror = true;
      setRotation(Stand, 0F, 0F, 0F);
      Stand_Connector = new ModelRenderer(this, 37, 53);
      Stand_Connector.addBox(0F, 0F, 0F, 8, 2, 8);
      Stand_Connector.setRotationPoint(-4F, 11F, -4F);
      Stand_Connector.setTextureSize(128, 128);
      Stand_Connector.mirror = true;
      setRotation(Stand_Connector, 0F, 0F, 0F);
      Battery = new ModelRenderer(this, 39, 23);
      Battery.addBox(0F, 0F, 0F, 12, 4, 4);
      Battery.setRotationPoint(-6F, 17F, -7F);
      Battery.setTextureSize(128, 128);
      Battery.mirror = true;
      setRotation(Battery, 0F, 0F, 0F);
      Cords_Stand = new ModelRenderer(this, 58, 37);
      Cords_Stand.addBox(0F, 0F, -3F, 2, 8, 1);
      Cords_Stand.setRotationPoint(-1F, 13F, 0F);
      Cords_Stand.setTextureSize(128, 128);
      Cords_Stand.mirror = true;
      setRotation(Cords_Stand, 0F, 0F, 0F);
      Battery_Top = new ModelRenderer(this, 67, 64);
      Battery_Top.addBox(0F, 0F, 0F, 12, 3, 5);
      Battery_Top.setRotationPoint(-6F, 16F, -8F);
      Battery_Top.setTextureSize(128, 128);
      Battery_Top.mirror = true;
      setRotation(Battery_Top, 0F, 0F, 0F);
      Cords_Monitor = new ModelRenderer(this, 64, 37);
      Cords_Monitor.addBox(0F, 0F, 0F, 4, 8, 1);
      Cords_Monitor.setRotationPoint(-2F, 4F, -9F);
      Cords_Monitor.setTextureSize(128, 128);
      Cords_Monitor.mirror = true;
      setRotation(Cords_Monitor, 0F, 0F, 0F);
      Cords_Link = new ModelRenderer(this, 74, 37);
      Cords_Link.addBox(0F, 0F, 1F, 4, 1, 4);
      Cords_Link.setRotationPoint(-2F, 11F, -9F);
      Cords_Link.setTextureSize(128, 128);
      Cords_Link.mirror = true;
      setRotation(Cords_Link, 0F, 0F, 0F);
  }
  
  public void render(float scale)
  {
    Base1.render(scale);
    Base2.render(scale);
    Leg1.render(scale);
    Leg2.render(scale);
    Leg3.render(scale);
    Leg4.render(scale);
    Keyboard_Bottom.render(scale);
    Keyboard_Top.render(scale);
    Monitor_Base.render(scale);
    Monitor_Bulk.render(scale);
    Top_Frame.render(scale);
    Side_Frame1.render(scale);
    Side_Frame2.render(scale);
    Stand.render(scale);
    Stand_Connector.render(scale);
    Battery.render(scale);
    Cords_Stand.render(scale);
    Battery_Top.render(scale);
    Cords_Monitor.render(scale);
    Cords_Link.render(scale);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
}
